
services:
  replicate-flux-lora:
    image: ghcr.io/rtuszik/replicate-flux-lora:latest
    container_name: replicate-flux-lora
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ${HOST_OUTPUT_DIR}:/app/output
      - replicate-flux-lora-settings:/app/settings
    restart: unless-stopped


volumes:
  replicate-flux-lora-settings: